name: test_react
on:
  push:
    branches: ['master'] # 你可以改成master看你自己
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1 下载代码
      - uses: actions/checkout@v3

      # 安装依赖
      - name: 安装依赖
        run: npm install

      # 打包
      - name: 开始打包
        run: npm run build

      # ssh
      - name: 部署到服务器
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          # 登陆ssh时候的 sshkey
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          # Remote host
          REMOTE_HOST: ${{ secrets.HOST }}
          # Remote user
          REMOTE_USER: ${{ secrets.USERNAME }}
          # Remote port
          SOURCE: ./test #一般是dist
          TARGET: /usr/local/nginx/html # 这里是项目存放在服务器的哪个文件下